name: Node.js Package

on:
  release:
    types: [created]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        eslint: [6.x, 5.x]
        node: [13.x, 12.x, 10.x, 8.x]
        exclude:
          # On Windows, run tests with only the latest LTS environments.
          - os: windows-latest
            eslint: 6.x
            node: 13.x
          - os: windows-latest
            eslint: 6.x
            node: 10.x
          - os: windows-latest
            eslint: 6.x
            node: 8.x
          - os: windows-latest
            eslint: 5.x
            node: 13.x
          - os: windows-latest
            eslint: 5.x
            node: 12.x
          - os: windows-latest
            eslint: 5.x
            node: 10.x
          - os: windows-latest
            eslint: 5.x
            node: 8.x
          # On macOS, run tests with only the latest LTS environments.
          - os: macOS-latest
            eslint: 6.x
            node: 13.x
          - os: macOS-latest
            eslint: 6.x
            node: 10.x
          - os: macOS-latest
            eslint: 6.x
            node: 8.x
          - os: macOS-latest
            eslint: 5.x
            node: 13.x
          - os: macOS-latest
            eslint: 5.x
            node: 12.x
          - os: macOS-latest
            eslint: 5.x
            node: 10.x
          - os: macOS-latest
            eslint: 5.x
            node: 8.x
          # Run ESLint 5.x tests on only the latest LTS Node.
          - os: ubuntu-latest
            eslint: 5.x
            node: 13.x
          - os: ubuntu-latest
            eslint: 5.x
            node: 10.x
          - os: ubuntu-latest
            eslint: 5.x
            node: 8.x

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install Packages
      run: npm ci
    - name: Install ESLint ${{ matrix.eslint }}
      # Need to execute this command twice because of npm's bug.
      # See also: https://npm.community/t/error-node-modules-staging-eslint-e7cf6846-node-modules-eslint
      run: |
        npm install --no-save eslint@${{ matrix.eslint }}
        npm install --no-save eslint@${{ matrix.eslint }}
    - name: Test
      run: npm test

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

  publish-gpr:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@fourjuaneight'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
