name: Test

on: [push]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        eslint: [6.x, 5.x]
        node: [13.x, 12.x, 10.x, 8.x]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install dependencies
      run: npm ci
    - name: Install ESLint ${{ matrix.eslint }}
      # Need to execute this command twice because of npm's bug.
      # See also: https://npm.community/t/error-node-modules-staging-eslint-e7cf6846-node-modules-eslint
      run: |
        npm install --no-save eslint@${{ matrix.eslint }}
        npm install --no-save eslint@${{ matrix.eslint }}
    - name: Install React for JSX testing
      run: npm install react
    - name: Test
      run: npm test
